#!/bin/sh

. /lib/functions.sh
. /lib/functions/system.sh

MAC=$(dd bs=1 skip=7 count=3 if=/dev/mtd2 2>/dev/null | hexdump -v -n 3 -e '3/1 "%02X"')
SSID=DM06_${MAC}

uci set wireless.ap.ssid="$SSID"

uci commit
return 0
